CREATE TABLE IF NOT EXISTS VEHICLE (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    MAKE VARCHAR(255) NOT NULL,
    MODEL VARCHAR(255) NOT NULL
    );

INSERT INTO VEHICLE (MAKE, MODEL) VALUES ('Toyota', 'Corolla');
INSERT INTO VEHICLE (MAKE, MODEL) VALUES ('Honda', 'Civic');